/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExamAppGistSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/settings.ts
var import_obsidian5 = require("obsidian");

// src/githubApi.ts
var import_obsidian = require("obsidian");
var GIST_FILENAME = "exam_app_backup.json";
var GITHUB_API_BASE = "https://api.github.com";
async function fetchGitHubUser(token) {
  if (!token || !token.trim()) {
    throw new Error("GitHub PAT token bo\u015F olamaz.");
  }
  const reqParams = {
    url: `${GITHUB_API_BASE}/user`,
    method: "GET",
    headers: {
      "Authorization": `Bearer ${token.trim()}`,
      "Accept": "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28"
    }
  };
  const response = await (0, import_obsidian.requestUrl)(reqParams);
  if (response.status === 401) {
    throw new Error("Ge\xE7ersiz GitHub PAT token veya s\xFCresi dolmu\u015F.");
  } else if (response.status !== 200) {
    throw new Error(`GitHub profil bilgisi al\u0131namad\u0131 (HTTP ${response.status})`);
  }
  const data = response.json;
  return {
    login: data.login,
    avatarUrl: data.avatar_url,
    name: data.name
  };
}
async function findExamAppGist(token) {
  var _a;
  if (!token || !token.trim()) return null;
  const reqParams = {
    url: `${GITHUB_API_BASE}/gists?per_page=100`,
    method: "GET",
    headers: {
      "Authorization": `Bearer ${token.trim()}`,
      "Accept": "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28"
    }
  };
  const response = await (0, import_obsidian.requestUrl)(reqParams);
  if (response.status !== 200) {
    throw new Error(`Gist listesi al\u0131namad\u0131 (HTTP ${response.status})`);
  }
  const gists = response.json;
  if (Array.isArray(gists)) {
    for (const gist of gists) {
      if (gist.files && (gist.files[GIST_FILENAME] || ((_a = gist.description) == null ? void 0 : _a.toLowerCase().includes("exam app")))) {
        return gist.id;
      }
    }
  }
  return null;
}
async function createExamAppGist(token) {
  if (!token || !token.trim()) {
    throw new Error("Gist olu\u015Fturmak i\xE7in ge\xE7erli bir token gerekiyor.");
  }
  const initialPayload = {
    version: 2,
    sources: [],
    deletedSourceIds: [],
    stats: {},
    totalStats: {},
    recentTests: {},
    settings: {}
  };
  const reqParams = {
    url: `${GITHUB_API_BASE}/gists`,
    method: "POST",
    headers: {
      "Authorization": `Bearer ${token.trim()}`,
      "Accept": "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({
      description: "Exam App - User Study & Resource Data Sync (via Obsidian)",
      public: false,
      files: {
        [GIST_FILENAME]: {
          content: JSON.stringify(initialPayload, null, 2)
        }
      }
    })
  };
  const response = await (0, import_obsidian.requestUrl)(reqParams);
  if (response.status !== 201 && response.status !== 200) {
    throw new Error(`ExamApp Gist olu\u015Fturulamad\u0131 (HTTP ${response.status})`);
  }
  return response.json.id;
}

// src/fileScanner.ts
var import_obsidian2 = require("obsidian");

// src/schemaValidator.ts
var VALID_TYPES = /* @__PURE__ */ new Set([
  "single_choice",
  "multiple_choice",
  "true_false",
  "short_answer",
  "text_input",
  "fill_in_the_blank",
  "flashcard",
  "reading",
  "topic_review",
  "text",
  "open_ended"
]);
function validateExamSchema(data) {
  var _a;
  if (!data || typeof data !== "object" || Array.isArray(data)) {
    return { valid: false, isExamAppSource: false };
  }
  if (!data.id || typeof data.id !== "string") {
    return { valid: false, isExamAppSource: false };
  }
  if (!Array.isArray(data.questions)) {
    return { valid: false, isExamAppSource: false };
  }
  for (let i = 0; i < data.questions.length; i++) {
    const q = data.questions[i];
    if (q.id === void 0 || q.id === null) {
      return { valid: false, isExamAppSource: true };
    }
    const text = ((_a = q.content) == null ? void 0 : _a.text) || q.text;
    if (!text || String(text).trim() === "") {
      return { valid: false, isExamAppSource: true };
    }
    if (!q.type || !VALID_TYPES.has(q.type)) {
      return { valid: false, isExamAppSource: true };
    }
    if (q.type !== "flashcard" && q.type !== "reading" && q.type !== "topic_review" && (!q.answer || typeof q.answer !== "object")) {
      return { valid: false, isExamAppSource: true };
    }
  }
  return { valid: true, isExamAppSource: true };
}

// src/fileScanner.ts
async function scanLocalSources(app, folderPath) {
  const targetFolder = app.vault.getAbstractFileByPath(folderPath);
  if (!targetFolder || !(targetFolder instanceof import_obsidian2.TFolder)) {
    console.warn(`[ExamApp Sync] Hedef klas\xF6r bulunamad\u0131: ${folderPath}`);
    return [];
  }
  const validSources = [];
  for (const child of targetFolder.children) {
    if (child instanceof import_obsidian2.TFile && child.extension === "json") {
      try {
        const content = await app.vault.read(child);
        if (!content || content.trim().length === 0) continue;
        const data = JSON.parse(content);
        const { valid, isExamAppSource } = validateExamSchema(data);
        if (isExamAppSource && valid) {
          validSources.push(data);
        } else if (isExamAppSource && !valid) {
          console.warn(`[ExamApp Sync] Dosya (${child.path}) ExamApp yap\u0131s\u0131na benziyor fakat \u015Fema hatas\u0131 i\xE7eriyor. Atlan\u0131yor.`);
        }
      } catch (err) {
        console.error(`[ExamApp Sync] JSON okuma hatas\u0131 (${child.path}):`, err);
      }
    }
  }
  return validSources;
}
async function writeLocalSources(app, folderPath, sources) {
  const targetFolder = app.vault.getAbstractFileByPath(folderPath);
  if (!targetFolder || !(targetFolder instanceof import_obsidian2.TFolder)) {
    try {
      await app.vault.createFolder(folderPath);
    } catch (e) {
      console.error(`[ExamApp Sync] Hedef klas\xF6r olu\u015Fturulamad\u0131: ${folderPath}`, e);
      return;
    }
  }
  for (const source of sources) {
    const safeName = (source.name || source.id || "Unknown_Source").replace(/[\\/:*?"<>|]/g, "_");
    const filePath = `${folderPath}/${safeName}_${source.id.substring(0, 8)}.json`;
    const content = JSON.stringify(source, null, 2);
    const existingFile = app.vault.getAbstractFileByPath(filePath);
    if (existingFile instanceof import_obsidian2.TFile) {
      await app.vault.modify(existingFile, content);
    } else {
      await app.vault.create(filePath, content);
    }
  }
}
async function cleanupOldDirectory(app, oldFolderPath, newFolderPath) {
  if (!oldFolderPath || oldFolderPath.trim() === "" || oldFolderPath === newFolderPath) {
    return 0;
  }
  const oldFolder = app.vault.getAbstractFileByPath(oldFolderPath);
  if (!oldFolder || !(oldFolder instanceof import_obsidian2.TFolder)) {
    return 0;
  }
  let deletedCount = 0;
  const children = [...oldFolder.children];
  for (const child of children) {
    if (!(child instanceof import_obsidian2.TFile)) continue;
    if (child.name === "examApp_data.md" || child.name === "ExamApp_Overview.md") {
      try {
        await app.vault.delete(child);
        deletedCount++;
      } catch (err) {
        console.error(`[ExamApp Sync] Failed to delete summary file in old directory (${child.path}):`, err);
      }
    } else if (child.extension === "json") {
      try {
        const content = await app.vault.read(child);
        const data = JSON.parse(content);
        const { isExamAppSource } = validateExamSchema(data);
        if (isExamAppSource) {
          await app.vault.delete(child);
          deletedCount++;
        }
      } catch (err) {
        console.error(`[ExamApp Sync] Failed during garbage collection of file (${child.path}):`, err);
      }
    }
  }
  if (oldFolder.children.length === 0) {
    try {
      await app.vault.delete(oldFolder);
    } catch (err) {
      console.warn(`[ExamApp Sync] Could not delete empty old directory (${oldFolderPath}):`, err);
    }
  }
  return deletedCount;
}

// src/markdownGenerator.ts
var import_obsidian3 = require("obsidian");
function getDatasetFilename(source) {
  var _a;
  const title = source.name || ((_a = source.exam_metadata) == null ? void 0 : _a.title) || source.title || source.id || "Unknown_Source";
  const safeName = title.replace(/[\\/:*?"<>|]/g, "_");
  const shortId = (source.id || "00000000").substring(0, 8);
  return `${safeName}_${shortId}.json`;
}
function getSummaryLocation(folderPath) {
  const normalized = folderPath.replace(/\\/g, "/").replace(/\/+$/, "");
  const lastSlashIndex = normalized.lastIndexOf("/");
  if (lastSlashIndex > 0) {
    const parentFolderPath = normalized.substring(0, lastSlashIndex);
    const relativeSubfolder = normalized.substring(lastSlashIndex + 1);
    return {
      parentFolderPath,
      relativeSubfolder
    };
  }
  return {
    parentFolderPath: normalized,
    relativeSubfolder: ""
  };
}
async function generateMarkdownSummary(app, folderPath, sources, syncStatus = "Success") {
  const { parentFolderPath, relativeSubfolder } = getSummaryLocation(folderPath);
  const summaryFilePath = `${parentFolderPath}/00_ExamApp_Overview.md`;
  let targetFolder = app.vault.getAbstractFileByPath(parentFolderPath);
  if (!targetFolder || !(targetFolder instanceof import_obsidian3.TFolder)) {
    try {
      await app.vault.createFolder(parentFolderPath);
    } catch (e) {
      console.error(`[ExamApp Sync] Failed to create directory for summary: ${parentFolderPath}`, e);
      return;
    }
  }
  const now = /* @__PURE__ */ new Date();
  const totalDatasets = sources.length;
  let totalQuestions = 0;
  sources.forEach((s) => {
    if (Array.isArray(s.questions)) {
      totalQuestions += s.questions.length;
    }
  });
  const formattedSyncTime = now.toISOString().replace("T", " ").substring(0, 19);
  let markdown = `# \u{1F4CA} ExamApp Datasets & Sync Overview

> [!abstract] System Overview
> - \u{1F4C1} **Total Datasets**: \`${totalDatasets}\`
> - \u2753 **Total Questions**: \`${totalQuestions}\`
> - \u{1F504} **Last Sync**: \`${formattedSyncTime}\` (\`${syncStatus}\`)
> - \u{1F4D8} **Guide & AI Prompt**: [[01_ExamApp_About.md|01_ExamApp_About.md]]

## \u{1F4D1} Datasets Index

| Dataset Title | Questions | App Version | Categories / Tags | Last Modified |
| :--- | :---: | :---: | :--- | :--- |
`;
  if (sources.length === 0) {
    markdown += `| *No datasets found* | 0 | - | - | - |
`;
  } else {
    sources.forEach((s) => {
      var _a, _b, _c;
      const title = s.name || ((_a = s.exam_metadata) == null ? void 0 : _a.title) || s.title || s.id || "Untitled Dataset";
      const fileName = getDatasetFilename(s);
      const relativeFilePath = relativeSubfolder ? `${relativeSubfolder}/${fileName}` : fileName;
      const qCount = Array.isArray(s.questions) ? s.questions.length : 0;
      const appVersion = s.target_version || s.version || ((_b = s.exam_metadata) == null ? void 0 : _b.version) || "N/A";
      let categories = "-";
      if (Array.isArray(s.categories) && s.categories.length > 0) {
        categories = s.categories.join(", ");
      } else if (Array.isArray(s.tags) && s.tags.length > 0) {
        categories = s.tags.join(", ");
      } else if ((_c = s.exam_metadata) == null ? void 0 : _c.category) {
        categories = String(s.exam_metadata.category);
      }
      let lastMod = "-";
      if (s.lastUsed || s.lastUpdated || s.updatedAt) {
        const ts = s.lastUsed || s.lastUpdated || s.updatedAt;
        try {
          lastMod = new Date(ts).toISOString().split("T")[0];
        } catch (e) {
          lastMod = String(ts);
        }
      }
      const safeTitle = title.replace(/\|/g, "\\|");
      const safeCategories = categories.replace(/\|/g, "\\|");
      markdown += `| [[${relativeFilePath}\\|${safeTitle}]] | ${qCount} | \`${appVersion}\` | ${safeCategories} | ${lastMod} |
`;
    });
  }
  const existingFile = app.vault.getAbstractFileByPath(summaryFilePath);
  if (existingFile instanceof import_obsidian3.TFile) {
    try {
      const currentContent = await app.vault.read(existingFile);
      if (currentContent !== markdown) {
        await app.vault.modify(existingFile, markdown);
      }
    } catch (e) {
      console.error(`[ExamApp Sync] Failed to update summary file: ${summaryFilePath}`, e);
    }
  } else {
    try {
      await app.vault.create(summaryFilePath, markdown);
    } catch (e) {
      console.error(`[ExamApp Sync] Failed to create summary file: ${summaryFilePath}`, e);
    }
  }
  await generateAboutExamAppMarkdown(app, parentFolderPath);
}
async function generateAboutExamAppMarkdown(app, parentFolderPath) {
  const aboutFilePath = `${parentFolderPath}/01_ExamApp_About.md`;
  const oldAboutFilePath = `${parentFolderPath}/01_About_ExamApp.md`;
  const oldFile = app.vault.getAbstractFileByPath(oldAboutFilePath);
  if (oldFile instanceof import_obsidian3.TFile) {
    try {
      await app.vault.delete(oldFile);
    } catch (e) {
    }
  }
  const markdown = `# \u{1F4D8} About ExamApp & AI Dataset Guide

> [!info] Open Source Project Reference
> **ExamApp** is an open-source, web-based interactive flashcard and exam preparation application.
> - \u{1F310} **GitHub Repository**: [https://github.com/tafirnat/exam-app](https://github.com/tafirnat/exam-app)
> - \u{1F4CA} **Dynamic Datasets Dashboard**: [[00_ExamApp_Overview.md|00_ExamApp_Overview.md]]

---


## \u{1F4A1} What is ExamApp?

**ExamApp** allows students, developers, and educators to create, manage, and study custom question banks (datasets). Key features include:
- Interactive flashcards with spaced repetition and confidence tracking.
- Multiple question format support (Single Choice, Multiple Choice, True/False, Flashcards, Open Ended/Text Input).
- Seamless synchronization with GitHub Gists and Obsidian Vault via the **Obsidian ExamApp Sync Plugin**.

---

## \u{1F916} AI & Human Dataset Schema Specification

To ensure any JSON dataset file is recognized and synced properly by ExamApp, it **must** strictly conform to the following JSON structure.

### 1. Root Dataset Schema

| Field | Type | Required | Description |
| :--- | :--- | :---: | :--- |
| \`id\` | \`string\` | **Yes** | Unique identifier (UUID v4 or slug string) |
| \`name\` / \`title\` | \`string\` | **Yes** | Title of the dataset / question pool |
| \`description\` | \`string\` | No | Short description of the dataset topic |
| \`target_version\` | \`string\` | No | Compatible ExamApp version (e.g. \`"1.0.0"\`) |
| \`categories\` / \`tags\` | \`array<string>\` | No | List of category names or tags |
| \`questions\` | \`array<object>\` | **Yes** | Array of question objects (defined below) |

### 2. Question Item Schema

| Field | Type | Required | Description |
| :--- | :--- | :---: | :--- |
| \`id\` | \`string\` | **Yes** | Unique ID within the dataset (e.g. \`"q_01"\`) |
| \`order\` | \`number\` | No | Sequence index (1, 2, 3...) |
| \`type\` | \`string\` | **Yes** | Question type: \`flashcard\`, \`single_choice\`, \`multiple_choice\`, \`true_false\`, \`open_ended\` |
| \`difficulty\` | \`number\` | No | Rating from 1 (Easy) to 5 (Hard) |
| \`tags\` | \`array<string>\` | No | Specific topic tags for this question |
| \`content\` | \`object\` | **Yes** | Must contain \`{ "text": "Question prompt here" }\` and option list if choice-based |
| \`answer\` | \`object\` | **Yes** | Structure depends on \`type\` (see examples below) |

---

## \u{1F4DD} Question Type Examples & Templates

### 1. Flashcard (\`flashcard\`)
- \`content.text\`: Front side of card (Question / Prompt)
- \`answer.back\`: Back side of card (Explanation / Answer)

\`\`\`json
{
  "id": "q_fc_01",
  "order": 1,
  "type": "flashcard",
  "difficulty": 2,
  "tags": ["Networking", "OSI"],
  "content": {
    "text": "What is the primary function of the OSI Network Layer (Layer 3)?"
  },
  "answer": {
    "back": "The Network Layer is responsible for packet forwarding including routing through intermediate routers."
  }
}
\`\`\`

### 2. Single Choice (\`single_choice\`)
- \`content.text\`: Question prompt
- \`content.options\`: Array of string options
- \`answer.correct\`: 0-based index of correct option

\`\`\`json
{
  "id": "q_sc_01",
  "order": 2,
  "type": "single_choice",
  "difficulty": 1,
  "tags": ["Protocols"],
  "content": {
    "text": "Which port is used by standard HTTPS by default?",
    "options": ["80", "443", "22", "8080"]
  },
  "answer": {
    "correct": 1
  }
}
\`\`\`

### 3. Multiple Choice (\`multiple_choice\`)
- \`content.text\`: Question prompt
- \`content.options\`: Array of string options
- \`answer.correct\`: Array of 0-based indices of correct options

\`\`\`json
{
  "id": "q_mc_01",
  "order": 3,
  "type": "multiple_choice",
  "difficulty": 3,
  "tags": ["Protocols"],
  "content": {
    "text": "Which of the following protocols operate at the Transport Layer (Layer 4)?",
    "options": ["TCP", "IP", "UDP", "HTTP"]
  },
  "answer": {
    "correct": [0, 2]
  }
}
\`\`\`

### 4. True / False (\`true_false\`)
- \`content.text\`: Statement
- \`answer.correct\`: Boolean \`true\` or \`false\`

\`\`\`json
{
  "id": "q_tf_01",
  "order": 4,
  "type": "true_false",
  "difficulty": 1,
  "tags": ["Security"],
  "content": {
    "text": "UDP provides connection-oriented reliable transmission with error checking."
  },
  "answer": {
    "correct": false
  }
}
\`\`\`

### 5. Open Ended / Text Input (\`open_ended\` / \`text_input\`)
- \`content.text\`: Question prompt
- \`answer.text\`: Reference answer string

\`\`\`json
{
  "id": "q_oe_01",
  "order": 5,
  "type": "open_ended",
  "difficulty": 3,
  "tags": ["Storage"],
  "content": {
    "text": "Explain the difference between RAID 0 and RAID 1 in terms of redundancy."
  },
  "answer": {
    "text": "RAID 0 offers striping without redundancy (data loss if one disk fails). RAID 1 offers mirroring with 100% data redundancy."
  }
}
\`\`\`

---

## \u26A1 Complete Dataset JSON Template

\`\`\`json
{
  "id": "sample-dataset-uuid-001",
  "name": "Sample ExamApp Dataset",
  "description": "Example question pool for testing and AI generation reference.",
  "target_version": "1.0.0",
  "categories": ["General Knowledge", "IT Basics"],
  "questions": [
    {
      "id": "q_01",
      "order": 1,
      "type": "flashcard",
      "difficulty": 2,
      "tags": ["Basics"],
      "content": {
        "text": "What is ExamApp?"
      },
      "answer": {
        "back": "ExamApp is an open-source web application for interactive studying and question management."
      }
    }
  ]
}
\`\`\`

---

## \u{1F916} AI Prompt Template (Copy & Paste for ChatGPT / Claude / Gemini)

You can copy and paste the following prompt into any AI assistant to automatically generate valid ExamApp question datasets matching the official open-source schema:

\`\`\`text
You are an expert AI dataset generator for ExamApp (Open Source Repository: https://github.com/tafirnat/exam-app).
Please generate a valid, high-quality ExamApp dataset JSON file for the topic: [YOUR TOPIC HERE].

Context & Repository Reference:
- GitHub Repository: https://github.com/tafirnat/exam-app
- App Version Compatibility: 1.0.0

Strict Schema Requirements:
1. Root JSON must contain:
   - "id": UUID string (e.g. "a1b2c3d4-e5f6-7890-abcd-1234567890ab")
   - "name": Topic Title (string)
   - "description": Brief overview of the topic / question set
   - "target_version": "1.0.0"
   - "categories": array of topic category strings
   - "questions": array of question objects
2. Each item in "questions" MUST have:
   - "id": string (unique ID within dataset, e.g. "q_01")
   - "order": number starting from 1
   - "type": "flashcard" | "single_choice" | "multiple_choice" | "true_false" | "open_ended"
   - "difficulty": number (1 = Easy to 5 = Hard)
   - "tags": array of strings
   - "content": object containing:
     - "text": question prompt / statement
     - "options": array of string choices (ONLY for "single_choice" and "multiple_choice")
   - "answer": object containing:
     - "back": explanation string (ONLY for "flashcard")
     - "correct": 0-based index (single_choice), array of indices (multiple_choice), or boolean (true_false)
     - "text": reference answer string (ONLY for "open_ended")
3. Return ONLY valid JSON, wrapped inside a \`\`\`json ... \`\`\` code block.
\`\`\`

---

## \u{1F517} Related Resources
- \u{1F4E6} **ExamApp Main GitHub Repository**: [https://github.com/tafirnat/exam-app](https://github.com/tafirnat/exam-app)
- \u{1F4CA} **Dynamic Datasets Dashboard**: [[00_ExamApp_Overview.md|00_ExamApp_Overview.md]]
`;
  const existingFile = app.vault.getAbstractFileByPath(aboutFilePath);
  if (existingFile instanceof import_obsidian3.TFile) {
    try {
      const currentContent = await app.vault.read(existingFile);
      if (currentContent !== markdown) {
        await app.vault.modify(existingFile, markdown);
      }
    } catch (e) {
      console.error(`[ExamApp Sync] Failed to update About file: ${aboutFilePath}`, e);
    }
  } else {
    try {
      await app.vault.create(aboutFilePath, markdown);
    } catch (e) {
      console.error(`[ExamApp Sync] Failed to create About file: ${aboutFilePath}`, e);
    }
  }
}

// src/updateChecker.ts
var import_obsidian4 = require("obsidian");
function isNewerVersion(remoteVer, currentVer) {
  const r = remoteVer.replace(/^v/, "").split(".").map(Number);
  const c = currentVer.replace(/^v/, "").split(".").map(Number);
  for (let i = 0; i < Math.max(r.length, c.length); i++) {
    const rv = r[i] || 0;
    const cv = c[i] || 0;
    if (rv > cv) return true;
    if (rv < cv) return false;
  }
  return false;
}
async function checkForUpdates(plugin, isManual = false) {
  const now = Date.now();
  const TWENTY_FOUR_HOURS = 24 * 60 * 60 * 1e3;
  if (!isManual) {
    if (!plugin.settings.autoCheckUpdates) return;
    if (now - plugin.settings.lastUpdateCheckTimestamp < TWENTY_FOUR_HOURS) return;
  }
  if (isManual && plugin.settings.showNotifications) {
    new import_obsidian4.Notice("[ExamApp Sync] Eklenti g\xFCncellemeleri kontrol ediliyor...");
  }
  try {
    plugin.settings.lastUpdateCheckTimestamp = now;
    await plugin.saveSettings();
    const currentVersion = plugin.manifest.version;
    let latestVersion = "";
    let downloadUrlMainJs = "";
    let downloadUrlManifest = "";
    try {
      const releaseRes = await (0, import_obsidian4.requestUrl)({
        url: "https://api.github.com/repos/tafirnat/obsidian-examapp-gist-sync/releases/latest",
        headers: { "User-Agent": "Obsidian-ExamApp-Sync-Plugin" }
      });
      if (releaseRes.status === 200) {
        const releaseData = releaseRes.json;
        latestVersion = (releaseData.tag_name || releaseData.name || "").replace(/^v/, "");
        const assets = releaseData.assets || [];
        const mainJsAsset = assets.find((a) => a.name === "main.js");
        const manifestAsset = assets.find((a) => a.name === "manifest.json");
        if (mainJsAsset) downloadUrlMainJs = mainJsAsset.browser_download_url;
        if (manifestAsset) downloadUrlManifest = manifestAsset.browser_download_url;
      }
    } catch (e) {
      console.log("[ExamApp Sync] Release API unavailable or no release tagged, checking raw main branch.");
    }
    if (!latestVersion) {
      try {
        const rawManifestRes = await (0, import_obsidian4.requestUrl)({
          url: "https://raw.githubusercontent.com/tafirnat/obsidian-examapp-gist-sync/main/manifest.json"
        });
        if (rawManifestRes.status === 200) {
          const remoteManifest = rawManifestRes.json;
          latestVersion = remoteManifest.version;
          downloadUrlMainJs = "https://raw.githubusercontent.com/tafirnat/obsidian-examapp-gist-sync/main/main.js";
          downloadUrlManifest = "https://raw.githubusercontent.com/tafirnat/obsidian-examapp-gist-sync/main/manifest.json";
        }
      } catch (e) {
        console.log("[ExamApp Sync] Raw GitHub main branch unreachable.");
      }
    }
    if (!latestVersion) {
      if (isManual && plugin.settings.showNotifications) {
        new import_obsidian4.Notice("[ExamApp Sync] G\xFCncelleme sunucusuna ula\u015F\u0131lamad\u0131 veya s\xFCr\xFCm bulunamad\u0131.");
      }
      return;
    }
    if (isNewerVersion(latestVersion, currentVersion)) {
      new import_obsidian4.Notice(`[ExamApp Sync] Yeni g\xFCncelleme mevcut: v${latestVersion} (Mevcut: v${currentVersion})`);
      if (plugin.settings.autoInstallUpdates && downloadUrlMainJs && downloadUrlManifest) {
        new import_obsidian4.Notice("[ExamApp Sync] Yeni eklenti dosyalar\u0131 indiriliyor...");
        const mainJsRes = await (0, import_obsidian4.requestUrl)({ url: downloadUrlMainJs });
        const manifestRes = await (0, import_obsidian4.requestUrl)({ url: downloadUrlManifest });
        if (mainJsRes.status === 200 && manifestRes.status === 200) {
          const pluginDir = plugin.manifest.dir;
          if (pluginDir) {
            const adapter = plugin.app.vault.adapter;
            await adapter.write(`${pluginDir}/main.js`, mainJsRes.text);
            await adapter.write(`${pluginDir}/manifest.json`, manifestRes.text);
            new import_obsidian4.Notice(`[ExamApp Sync] Eklenti v${latestVersion} s\xFCr\xFCm\xFCne g\xFCncellendi! L\xFCtfen eklentiyi veya Obsidian'\u0131 yeniden ba\u015Flat\u0131n.`);
          }
        }
      }
    } else {
      if (isManual && plugin.settings.showNotifications) {
        new import_obsidian4.Notice(`[ExamApp Sync] Eklentiniz g\xFCncel! (v${currentVersion})`);
      }
    }
  } catch (err) {
    console.error("[ExamApp Sync] G\xFCncelleme kontrol\xFC hatas\u0131:", err);
    if (isManual && plugin.settings.showNotifications) {
      new import_obsidian4.Notice(`[ExamApp Sync] G\xFCncelleme kontrol\xFC hatas\u0131: ${err.message}`);
    }
  }
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  githubToken: "",
  gistId: "",
  localFolderPath: "ExamApp Sync",
  githubUsername: "",
  autoSyncOnStartup: false,
  showNotifications: true,
  autoCheckUpdates: true,
  lastUpdateCheckTimestamp: 0,
  autoInstallUpdates: true
};
var ICONS = {
  github: `<svg height="16" width="16" viewBox="0 0 16 16" fill="currentColor" style="vertical-align: text-bottom; margin-right: 6px;"><path d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z"></path></svg>`,
  key: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: text-bottom; margin-right: 8px;"><path d="M21 2l-2 2m-1.5 1.5l-3 3m-5 5a7 7 0 1 1 3-3l7-7v3h3v3h-3z"/></svg>`,
  syncInfinity: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: text-bottom; margin-right: 8px;"><path d="M 12,12 C 8.5,16.5 4,17 2.5,14.5 C 1,12 2.5,8 6.5,8.5 C 10.5,9 13.5,14.5 17.5,15.5 C 21.5,16.5 23,12.5 21.5,10 C 20,7.5 16,7.5 12,12"/><path d="M 17,6.5 L 21.5,10 L 21,5.5"/><path d="M 7,17.5 L 2.5,14.5 L 3,19"/></svg>`,
  folder: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: text-bottom; margin-right: 8px;"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/></svg>`,
  sliders: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: text-bottom; margin-right: 8px;"><line x1="4" y1="21" x2="4" y2="14"/><line x1="4" y1="10" x2="4" y2="3"/><line x1="12" y1="21" x2="12" y2="12"/><line x1="12" y1="8" x2="12" y2="3"/><line x1="20" y1="21" x2="20" y2="16"/><line x1="20" y1="12" x2="20" y2="3"/><line x1="1" y1="14" x2="7" y2="14"/><line x1="9" y1="8" x2="15" y2="8"/><line x1="17" y1="16" x2="23" y2="16"/></svg>`,
  info: `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="examapp-info-icon" style="vertical-align: middle; margin-left: 6px; cursor: pointer; opacity: 0.6; transition: opacity 0.2s;" title="PAT Hakk\u0131nda Detayl\u0131 Bilgi"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>`,
  checkBadge: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--text-success)" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: middle; margin-right: 4px;"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>`,
  alertBadge: `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--text-accent)" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: middle; margin-right: 4px;"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>`,
  externalLink: `<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: middle; margin-left: 4px;"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>`,
  shield: `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--interactive-accent)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: text-bottom; margin-right: 6px;"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
  refresh: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: text-bottom; margin-right: 8px;"><polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/></svg>`
};
var ExamAppGistSyncSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    var _a;
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ExamApp Gist Sync - Ayarlar" });
    const authHeader = containerEl.createEl("h3");
    authHeader.innerHTML = `${ICONS.key}GitHub Oturum Y\xF6netimi`;
    if (this.plugin.settings.githubToken && this.plugin.settings.githubUsername) {
      const accountCard = containerEl.createDiv({ cls: "examapp-account-card" });
      accountCard.style.padding = "14px";
      accountCard.style.borderRadius = "8px";
      accountCard.style.backgroundColor = "var(--background-secondary)";
      accountCard.style.border = "1px solid var(--background-modifier-border)";
      accountCard.style.marginBottom = "18px";
      const statusEl = accountCard.createEl("div");
      statusEl.innerHTML = `${ICONS.github}<strong>Ba\u011Fl\u0131 Hesap:</strong> @${this.plugin.settings.githubUsername} <span style="color: var(--text-success); font-weight: bold; margin-left: 8px;">${ICONS.checkBadge}Aktif</span>`;
      statusEl.style.fontSize = "1.05em";
      statusEl.style.marginBottom = "12px";
      new import_obsidian5.Setting(accountCard).setName("Oturumu Kapat").setDesc("GitHub ba\u011Flant\u0131s\u0131n\u0131 ve kaydedilen Gist kimli\u011Fini kald\u0131r\u0131r.").addButton(
        (button) => button.setButtonText("Oturumu Kapat").setWarning().onClick(async () => {
          this.plugin.settings.githubToken = "";
          this.plugin.settings.githubUsername = "";
          this.plugin.settings.gistId = "";
          await this.plugin.saveSettings();
          new import_obsidian5.Notice("[ExamApp Sync] GitHub oturumu kapat\u0131ld\u0131.");
          this.display();
        })
      );
    } else {
      let inputToken = "";
      let showInfo = false;
      const loginSetting = new import_obsidian5.Setting(containerEl);
      const nameEl = loginSetting.nameEl;
      nameEl.innerHTML = `GitHub Personal Access Token (PAT) ${ICONS.info}`;
      loginSetting.setDesc('GitHub hesab\u0131n\u0131zdan al\u0131nan ("gist" yetkisine sahip) token. Oturum a\xE7\u0131ld\u0131\u011F\u0131nda senkronizasyon otomatik ba\u015Flar.');
      loginSetting.addText(
        (text) => text.setPlaceholder("ghp_...").setValue(this.plugin.settings.githubToken).onChange((val) => {
          inputToken = val.trim();
        })
      );
      (_a = loginSetting.controlEl.querySelector("input")) == null ? void 0 : _a.setAttribute("type", "password");
      const infoBox = containerEl.createDiv({ cls: "examapp-pat-info-box" });
      infoBox.style.display = "none";
      infoBox.style.padding = "14px 16px";
      infoBox.style.borderRadius = "8px";
      infoBox.style.backgroundColor = "var(--background-secondary)";
      infoBox.style.borderLeft = "4px solid var(--interactive-accent)";
      infoBox.style.marginBottom = "16px";
      infoBox.style.fontSize = "0.92em";
      infoBox.style.lineHeight = "1.5";
      infoBox.innerHTML = `
				<div style="font-weight: bold; font-size: 1.05em; margin-bottom: 6px;">PAT (Personal Access Token) Nedir ve Nas\u0131l Al\u0131n\u0131r?</div>
				<p style="margin: 0 0 10px 0; color: var(--text-normal);">
					<strong>Nedir?</strong> GitHub, g\xFCvenlik gerek\xE7esiyle \xFC\xE7\xFCnc\xFC taraf uygulamalar\u0131n kullan\u0131c\u0131 ad\u0131/\u015Fifre ile do\u011Frudan giri\u015F yapmas\u0131n\u0131 yasaklar. 
					PAT, ana \u015Fifrenizi vermeden sadece soru havuzlar\u0131n\u0131z\u0131 yedeklememiz i\xE7in verilen <strong>g\xFCvenli bir eri\u015Fim anahtar\u0131d\u0131r</strong>.
				</p>
				<div style="font-weight: bold; margin-bottom: 4px;">3 Ad\u0131mda Kolayca Al\u0131n:</div>
				<ol style="margin: 0 0 12px 18px; padding: 0;">
					<li style="margin-bottom: 6px;">
						<a href="https://github.com/settings/tokens/new?scopes=gist&description=Obsidian%20ExamApp%20Sync" target="_blank" style="color: var(--text-accent); font-weight: bold; text-decoration: underline;">
							GitHub Token Olu\u015Fturma Sayfas\u0131n\u0131 A\xE7\u0131n ${ICONS.externalLink}
						</a>
						<br><span style="color: var(--text-muted); font-size: 0.9em;">(Gereken "gist" yetkisi otomatik se\xE7ili gelecektir)</span>
					</li>
					<li style="margin-bottom: 4px;">Sayfan\u0131n en alt\u0131ndaki <strong>"Generate token"</strong> butonuna bas\u0131n.</li>
					<li>Ekranda \xE7\u0131kan <code>ghp_...</code> ile ba\u015Flayan kodu kopyalay\u0131p yukar\u0131daki alana yap\u0131\u015Ft\u0131r\u0131n.</li>
				</ol>
			`;
      const iconEl = nameEl.querySelector(".examapp-info-icon");
      if (iconEl) {
        iconEl.addEventListener("click", () => {
          showInfo = !showInfo;
          infoBox.style.display = showInfo ? "block" : "none";
        });
        iconEl.addEventListener("mouseenter", () => {
          iconEl.style.opacity = "1";
        });
        iconEl.addEventListener("mouseleave", () => {
          iconEl.style.opacity = "0.6";
        });
      }
      loginSetting.addButton((button) => {
        button.buttonEl.innerHTML = `${ICONS.github} GitHub ile Oturum A\xE7`;
        button.buttonEl.style.backgroundColor = "#24292f";
        button.buttonEl.style.color = "#ffffff";
        button.buttonEl.style.fontWeight = "600";
        button.buttonEl.style.padding = "6px 14px";
        button.buttonEl.style.borderRadius = "6px";
        button.buttonEl.style.border = "none";
        button.buttonEl.style.cursor = "pointer";
        button.buttonEl.style.display = "inline-flex";
        button.buttonEl.style.alignItems = "center";
        button.buttonEl.style.transition = "background-color 0.2s ease";
        button.buttonEl.addEventListener("mouseenter", () => {
          button.buttonEl.style.backgroundColor = "#333942";
        });
        button.buttonEl.addEventListener("mouseleave", () => {
          button.buttonEl.style.backgroundColor = "#24292f";
        });
        button.onClick(async () => {
          const tokenToUse = inputToken || this.plugin.settings.githubToken;
          if (!tokenToUse) {
            new import_obsidian5.Notice("[ExamApp Sync] L\xFCtfen bir GitHub PAT token girin.");
            return;
          }
          button.setDisabled(true);
          button.buttonEl.innerHTML = `${ICONS.github} Oturum A\xE7\u0131l\u0131yor...`;
          try {
            const user = await fetchGitHubUser(tokenToUse);
            this.plugin.settings.githubToken = tokenToUse;
            this.plugin.settings.githubUsername = user.login;
            let detectedGistId = await findExamAppGist(tokenToUse);
            if (!detectedGistId) {
              detectedGistId = await createExamAppGist(tokenToUse);
            }
            this.plugin.settings.gistId = detectedGistId;
            await this.plugin.saveSettings();
            new import_obsidian5.Notice(`[ExamApp Sync] Ho\u015F geldiniz @${user.login}! Oturum a\xE7\u0131ld\u0131. Senkronizasyon ba\u015Flat\u0131l\u0131yor...`);
            await this.plugin.syncWithGist();
            this.display();
          } catch (err) {
            console.error("[ExamApp Login Error]", err);
            new import_obsidian5.Notice(`[ExamApp Sync] Oturum A\xE7ma Ba\u015Far\u0131s\u0131z: ${err.message}`);
          } finally {
            button.setDisabled(false);
            button.buttonEl.innerHTML = `${ICONS.github} GitHub ile Oturum A\xE7`;
          }
        });
      });
    }
    if (this.plugin.settings.githubToken) {
      const gistHeader = containerEl.createEl("h3");
      gistHeader.innerHTML = `${ICONS.syncInfinity}Gist Durumu & Otomatik Tespit`;
      const gistCard = containerEl.createDiv();
      gistCard.style.padding = "12px";
      gistCard.style.borderRadius = "6px";
      gistCard.style.backgroundColor = "var(--background-secondary)";
      gistCard.style.marginBottom = "18px";
      if (this.plugin.settings.gistId) {
        const infoEl = gistCard.createEl("div");
        infoEl.innerHTML = `${ICONS.checkBadge}<strong>Ba\u011Fl\u0131 Gist ID:</strong> <code>${this.plugin.settings.gistId}</code> <span style="color: var(--text-muted); font-size: 0.9em;">(Otomatik Ba\u011Fland\u0131)</span>`;
        infoEl.style.marginBottom = "10px";
      } else {
        const infoEl = gistCard.createEl("div");
        infoEl.innerHTML = `${ICONS.alertBadge}<strong>Hen\xFCz bir ExamApp Gist ba\u011Fl\u0131 de\u011Fil.</strong>`;
        infoEl.style.color = "var(--text-accent)";
        infoEl.style.marginBottom = "10px";
      }
      new import_obsidian5.Setting(gistCard).setName("Gist Otomatik Yeniden Tara / Olu\u015Ftur").setDesc("Hesab\u0131n\u0131zdaki ExamApp Gist varl\u0131\u011F\u0131n\u0131 tarar veya yoksa otomatik olu\u015Fturur.").addButton(
        (btn) => btn.setButtonText("Yeniden Tara").onClick(async () => {
          try {
            const id = await findExamAppGist(this.plugin.settings.githubToken);
            if (id) {
              this.plugin.settings.gistId = id;
              await this.plugin.saveSettings();
              new import_obsidian5.Notice("[ExamApp Sync] ExamApp Gist ba\u015Far\u0131yla tespit edildi.");
              this.display();
            } else {
              new import_obsidian5.Notice("[ExamApp Sync] Hesab\u0131n\u0131zda hen\xFCz ExamApp Gist bulunamad\u0131.");
            }
          } catch (e) {
            new import_obsidian5.Notice(`[ExamApp Sync] Taramada hata: ${e.message}`);
          }
        })
      ).addButton(
        (btn) => btn.setButtonText("Yeni Gist Olu\u015Ftur").setCta().onClick(async () => {
          try {
            const newId = await createExamAppGist(this.plugin.settings.githubToken);
            this.plugin.settings.gistId = newId;
            await this.plugin.saveSettings();
            new import_obsidian5.Notice("[ExamApp Sync] Yeni ExamApp Gist olu\u015Fturuldu ve ba\u011Fland\u0131.");
            this.display();
          } catch (e) {
            new import_obsidian5.Notice(`[ExamApp Sync] Gist olu\u015Fturma hatas\u0131: ${e.message}`);
          }
        })
      );
      const detailsEl = containerEl.createEl("details");
      detailsEl.style.marginBottom = "18px";
      detailsEl.style.cursor = "pointer";
      const summaryEl = detailsEl.createEl("summary");
      summaryEl.innerHTML = `${ICONS.sliders} Geli\u015Fmi\u015F: Manuel Gist ID D\xFCzenleme`;
      summaryEl.style.color = "var(--text-muted)";
      summaryEl.style.fontWeight = "bold";
      new import_obsidian5.Setting(detailsEl).setName("Manuel Gist ID (\xD6zel)").setDesc("Gist ID otomatik tespit edilir. Yaln\u0131zca \xF6zel bir Gist ID zorlamak istiyorsan\u0131z de\u011Fi\u015Ftirin.").addText(
        (text) => text.setPlaceholder("e.g. 1a2b3c4d5e6f7g8h9i0j").setValue(this.plugin.settings.gistId).onChange(async (val) => {
          this.plugin.settings.gistId = val.trim();
          await this.plugin.saveSettings();
        })
      );
    }
    const folderHeader = containerEl.createEl("h3");
    folderHeader.innerHTML = `${ICONS.folder}Vault Senkronizasyon Klas\xF6r\xFC`;
    new import_obsidian5.Setting(containerEl).setName("Klas\xF6r Yolu").setDesc("Senkronize edilecek JSON dosyalar\u0131n\u0131n ve ExamApp_Overview.md \xF6zet panosunun bulundu\u011Fu Vault i\xE7i klas\xF6r.").addText(
      (text) => text.setPlaceholder("ExamApp Sync").setValue(this.plugin.settings.localFolderPath).onChange(async (val) => {
        const oldFolderPath = this.plugin.settings.localFolderPath;
        const newFolderPath = val.trim() || "ExamApp Sync";
        if (oldFolderPath === newFolderPath) {
          return;
        }
        let sources = await scanLocalSources(this.app, oldFolderPath);
        const deletedCount = await cleanupOldDirectory(this.app, oldFolderPath, newFolderPath);
        this.plugin.settings.localFolderPath = newFolderPath;
        await this.plugin.saveSettings();
        const newFolderSources = await scanLocalSources(this.app, newFolderPath);
        if (sources.length === 0 && newFolderSources.length > 0) {
          sources = newFolderSources;
        }
        if (sources.length > 0) {
          await writeLocalSources(this.app, newFolderPath, sources);
        }
        await generateMarkdownSummary(this.app, newFolderPath, sources, "Success");
        if (this.plugin.settings.showNotifications) {
          new import_obsidian5.Notice(`[ExamApp Sync] Klas\xF6r de\u011Fi\u015Ftirildi. Eski konumdan ${deletedCount} dosya temizlendi, veriler "${newFolderPath}" klas\xF6r\xFCne ta\u015F\u0131nd\u0131.`);
        }
      })
    );
    const schemaInfoBox = containerEl.createDiv();
    schemaInfoBox.style.padding = "10px 14px";
    schemaInfoBox.style.borderRadius = "6px";
    schemaInfoBox.style.backgroundColor = "var(--background-secondary)";
    schemaInfoBox.style.borderLeft = "4px solid var(--interactive-accent)";
    schemaInfoBox.style.marginBottom = "12px";
    schemaInfoBox.style.fontSize = "0.92em";
    schemaInfoBox.innerHTML = `${ICONS.shield} <strong>\u015Eema G\xFCvenlik Filtresi:</strong> Bu klas\xF6r i\xE7erisindeki dosyalar taran\u0131rken sadece ge\xE7erli ExamApp soru \u015Femas\u0131na (<code>{ id, questions: [...] }</code>) sahip <code>.json</code> dosyalar\u0131 i\u015Flenir. Di\u011Fer uyumsuz JSON veya not dosyalar\u0131 g\xFCvenle atlan\u0131r.`;
    new import_obsidian5.Setting(containerEl).setName("Klas\xF6r Taramas\u0131n\u0131 Test Et").setDesc("Belirtilen klas\xF6rdeki uyumlu ExamApp soru havuzlar\u0131n\u0131 canl\u0131 olarak tarar ve say\u0131s\u0131n\u0131 do\u011Frular.").addButton(
      (btn) => btn.setButtonText("\u015Eimdi Tara ve Do\u011Frula").onClick(async () => {
        const sources = await scanLocalSources(this.app, this.plugin.settings.localFolderPath);
        new import_obsidian5.Notice(`[ExamApp Sync] Tarama Tamamland\u0131: "${this.plugin.settings.localFolderPath}" klas\xF6r\xFCnde ${sources.length} adet ge\xE7erli ExamApp soru havuzu bulundu.`);
      })
    );
    const settingsHeader = containerEl.createEl("h3");
    settingsHeader.innerHTML = `${ICONS.sliders}Genel Otomasyon Ayarlar\u0131`;
    new import_obsidian5.Setting(containerEl).setName("Obsidian A\xE7\u0131l\u0131\u015F\u0131nda Otomatik Senkronize Et").setDesc("Obsidian ba\u015Flat\u0131ld\u0131\u011F\u0131nda Gist senkronizasyonunu arka planda otomatik olarak tetikler.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSyncOnStartup).onChange(async (val) => {
        this.plugin.settings.autoSyncOnStartup = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Senkronizasyon Bildirimlerini G\xF6ster").setDesc("Senkronizasyon ba\u015Flad\u0131\u011F\u0131nda ve tamamland\u0131\u011F\u0131nda ekranda bilgi bildirimleri (toast Notice) g\xF6sterir.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showNotifications).onChange(async (val) => {
        this.plugin.settings.showNotifications = val;
        await this.plugin.saveSettings();
      })
    );
    const updateHeader = containerEl.createEl("h3");
    updateHeader.innerHTML = `${ICONS.refresh}Eklenti G\xFCncellemeleri`;
    new import_obsidian5.Setting(containerEl).setName("Arka Planda Otomatik G\xFCncelleme Kontrol\xFC").setDesc("Obsidian a\xE7\u0131ld\u0131ktan 10 saniye sonra, 24 saatte bir arka planda g\xFCncellemeleri kontrol eder (A\xE7\u0131l\u0131\u015F performans\u0131na y\xFCk bindirmez).").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoCheckUpdates).onChange(async (val) => {
        this.plugin.settings.autoCheckUpdates = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("G\xFCncellemeleri Otomatik \u0130ndir ve Kur").setDesc("Yeni bir s\xFCr\xFCm tespit edildi\u011Finde eklenti dosyalar\u0131n\u0131 otomatik g\xFCnceller.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoInstallUpdates).onChange(async (val) => {
        this.plugin.settings.autoInstallUpdates = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("G\xFCncellemeleri \u015Eimdi Kontrol Et").setDesc(`Mevcut S\xFCr\xFCm: v${this.plugin.manifest.version}. GitHub deposundaki en son s\xFCr\xFCm\xFC canl\u0131 olarak kontrol eder.`).addButton(
      (btn) => btn.setButtonText("\u015Eimdi Kontrol Et").setCta().onClick(async () => {
        btn.setDisabled(true);
        btn.setButtonText("Kontrol Ediliyor...");
        try {
          await checkForUpdates(this.plugin, true);
        } finally {
          btn.setDisabled(false);
          btn.setButtonText("\u015Eimdi Kontrol Et");
        }
      })
    );
  }
};

// src/gistSync.ts
var import_obsidian6 = require("obsidian");
var GIST_FILENAME2 = "exam_app_backup.json";
var GITHUB_API_BASE2 = "https://api.github.com";
async function ensureGistId(settings) {
  if (!settings.githubToken) {
    throw new Error("GitHub PAT token tan\u0131ml\u0131 de\u011Fil. L\xFCtfen eklenti ayarlar\u0131ndan oturum a\xE7\u0131n.");
  }
  if (settings.gistId) {
    return settings.gistId;
  }
  const detectedId = await findExamAppGist(settings.githubToken);
  if (detectedId) {
    settings.gistId = detectedId;
    return detectedId;
  }
  const createdId = await createExamAppGist(settings.githubToken);
  settings.gistId = createdId;
  return createdId;
}
async function fetchGistData(settings) {
  const gistId = await ensureGistId(settings);
  const reqParams = {
    url: `${GITHUB_API_BASE2}/gists/${gistId}`,
    method: "GET",
    headers: {
      "Authorization": `Bearer ${settings.githubToken.trim()}`,
      "Accept": "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28"
    }
  };
  const response = await (0, import_obsidian6.requestUrl)(reqParams);
  if (response.status !== 200) {
    throw new Error(`GitHub Gist okuma hatas\u0131: ${response.status}`);
  }
  const gist = response.json;
  const file = gist.files && gist.files[GIST_FILENAME2];
  if (file) {
    let contentStr = file.content;
    if (file.truncated && file.raw_url) {
      const rawResponse = await (0, import_obsidian6.requestUrl)({
        url: file.raw_url,
        headers: {
          "Authorization": `Bearer ${settings.githubToken.trim()}`
        }
      });
      if (rawResponse.status === 200) {
        contentStr = rawResponse.text;
      }
    }
    if (contentStr && contentStr.trim().length > 0) {
      return JSON.parse(contentStr);
    }
  }
  return {
    version: 3,
    lastUpdated: Date.now(),
    sources: [],
    folders: [],
    deletedSourceIds: [],
    deletedFolderIds: [],
    stats: {},
    totalStats: {},
    recentTests: [],
    settings: {}
  };
}
async function pushGistData(settings, payload) {
  const gistId = await ensureGistId(settings);
  const reqParams = {
    url: `${GITHUB_API_BASE2}/gists/${gistId}`,
    method: "PATCH",
    headers: {
      "Authorization": `Bearer ${settings.githubToken.trim()}`,
      "Accept": "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({
      description: "Exam App - User Study & Resource Data Sync (via Obsidian)",
      files: {
        [GIST_FILENAME2]: {
          content: JSON.stringify(payload, null, 2)
        }
      }
    })
  };
  const response = await (0, import_obsidian6.requestUrl)(reqParams);
  if (response.status !== 200) {
    throw new Error(`GitHub Gist yazma hatas\u0131: ${response.status}`);
  }
}

// src/dataMerger.ts
function mergeSyncData(localSources, remotePayload) {
  let hasLocalChanges = false;
  const mergedDeletedSourceIds = Array.from(/* @__PURE__ */ new Set([
    ...(remotePayload == null ? void 0 : remotePayload.deletedSourceIds) || []
  ]));
  const mergedDeletedFolderIds = Array.from(/* @__PURE__ */ new Set([
    ...(remotePayload == null ? void 0 : remotePayload.deletedFolderIds) || []
  ]));
  const activeFolders = ((remotePayload == null ? void 0 : remotePayload.folders) || []).filter(
    (f) => f && f.id && !mergedDeletedFolderIds.includes(f.id)
  );
  const sourcesMap = /* @__PURE__ */ new Map();
  ((remotePayload == null ? void 0 : remotePayload.sources) || []).forEach((s) => {
    if (s && s.id && !mergedDeletedSourceIds.includes(s.id)) {
      sourcesMap.set(s.id, s);
    }
  });
  (localSources || []).forEach((s) => {
    if (!s || !s.id || mergedDeletedSourceIds.includes(s.id)) return;
    if (!sourcesMap.has(s.id)) {
      sourcesMap.set(s.id, s);
      hasLocalChanges = true;
    } else {
      const existing = sourcesMap.get(s.id);
      const localHasQuestions = Array.isArray(s.questions) && s.questions.length > 0;
      const existingHasQuestions = Array.isArray(existing.questions) && existing.questions.length > 0;
      if (!existingHasQuestions && localHasQuestions) {
        sourcesMap.set(s.id, s);
        hasLocalChanges = true;
      } else if (existingHasQuestions && !localHasQuestions) {
      } else if ((s.lastUsed || 0) > (existing.lastUsed || 0)) {
        sourcesMap.set(s.id, s);
        hasLocalChanges = true;
      }
    }
  });
  const mergedSources = Array.from(sourcesMap.values());
  return {
    version: 3,
    lastUpdated: Date.now(),
    sources: mergedSources,
    folders: activeFolders,
    deletedSourceIds: mergedDeletedSourceIds,
    deletedFolderIds: mergedDeletedFolderIds,
    stats: (remotePayload == null ? void 0 : remotePayload.stats) || {},
    totalStats: (remotePayload == null ? void 0 : remotePayload.totalStats) || {},
    recentTests: (remotePayload == null ? void 0 : remotePayload.recentTests) || [],
    settings: (remotePayload == null ? void 0 : remotePayload.settings) || {},
    hasLocalChanges
  };
}

// src/main.ts
var INFINITY_SYNC_ICON_SVG = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M 12,12 C 8.5,16.5 4,17 2.5,14.5 C 1,12 2.5,8 6.5,8.5 C 10.5,9 13.5,14.5 17.5,15.5 C 21.5,16.5 23,12.5 21.5,10 C 20,7.5 16,7.5 12,12"/><path d="M 17,6.5 L 21.5,10 L 21,5.5"/><path d="M 7,17.5 L 2.5,14.5 L 3,19"/></svg>`;
var ExamAppGistSyncPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.loadSettings();
    (0, import_obsidian7.addIcon)("examapp-infinity-sync", INFINITY_SYNC_ICON_SVG);
    this.addSettingTab(new ExamAppGistSyncSettingTab(this.app, this));
    const ribbonIconEl = this.addRibbonIcon("examapp-infinity-sync", "ExamApp Sync", async () => {
      await this.syncWithGist();
    });
    ribbonIconEl.addClass("examapp-sync-ribbon-class");
    this.addCommand({
      id: "sync-examapp-gist",
      name: "Sync with ExamApp Gist",
      callback: async () => {
        await this.syncWithGist();
      }
    });
    if (this.settings.autoSyncOnStartup && this.settings.githubToken) {
      this.app.workspace.onLayoutReady(async () => {
        await this.syncWithGist(true);
      });
    }
    this.app.workspace.onLayoutReady(() => {
      setTimeout(async () => {
        await checkForUpdates(this, false);
      }, 1e4);
    });
  }
  onunload() {
  }
  async syncWithGist(isAutoSync = false) {
    if (!this.settings.githubToken) {
      if (!isAutoSync && this.settings.showNotifications) {
        new import_obsidian7.Notice("[ExamApp Sync] L\xFCtfen \xF6nce eklenti ayarlar\u0131ndan GitHub hesab\u0131n\u0131zla oturum a\xE7\u0131n.");
      }
      return;
    }
    if (this.settings.showNotifications) {
      new import_obsidian7.Notice("[ExamApp Sync] Senkronizasyon ba\u015Flat\u0131l\u0131yor...");
    }
    try {
      const remoteData = await fetchGistData(this.settings);
      await this.saveSettings();
      const localSources = await scanLocalSources(this.app, this.settings.localFolderPath);
      const mergedData = mergeSyncData(localSources, remoteData);
      await pushGistData(this.settings, mergedData);
      await writeLocalSources(this.app, this.settings.localFolderPath, mergedData.sources);
      await generateMarkdownSummary(this.app, this.settings.localFolderPath, mergedData.sources, "Success");
      if (this.settings.showNotifications) {
        new import_obsidian7.Notice(`[ExamApp Sync] Senkronizasyon tamamland\u0131 (${mergedData.sources.length} havuz senkronize edildi).`);
      }
    } catch (error) {
      console.error("[ExamApp Sync] Hata:", error);
      if (this.settings.showNotifications) {
        new import_obsidian7.Notice(`[ExamApp Sync] Senkronizasyon hatas\u0131: ${error.message}`);
      }
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
