/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExamAppGistSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian3 = require("obsidian");

// src/githubApi.ts
var import_obsidian = require("obsidian");
var GIST_FILENAME = "exam_app_backup.json";
var GITHUB_API_BASE = "https://api.github.com";
async function fetchGitHubUser(token) {
  if (!token || !token.trim()) {
    throw new Error("GitHub PAT token bo\u015F olamaz.");
  }
  const reqParams = {
    url: `${GITHUB_API_BASE}/user`,
    method: "GET",
    headers: {
      "Authorization": `Bearer ${token.trim()}`,
      "Accept": "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28"
    }
  };
  const response = await (0, import_obsidian.requestUrl)(reqParams);
  if (response.status === 401) {
    throw new Error("Ge\xE7ersiz GitHub PAT token veya s\xFCresi dolmu\u015F.");
  } else if (response.status !== 200) {
    throw new Error(`GitHub profil bilgisi al\u0131namad\u0131 (HTTP ${response.status})`);
  }
  const data = response.json;
  return {
    login: data.login,
    avatarUrl: data.avatar_url,
    name: data.name
  };
}
async function findExamAppGist(token) {
  var _a;
  if (!token || !token.trim()) return null;
  const reqParams = {
    url: `${GITHUB_API_BASE}/gists?per_page=100`,
    method: "GET",
    headers: {
      "Authorization": `Bearer ${token.trim()}`,
      "Accept": "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28"
    }
  };
  const response = await (0, import_obsidian.requestUrl)(reqParams);
  if (response.status !== 200) {
    throw new Error(`Gist listesi al\u0131namad\u0131 (HTTP ${response.status})`);
  }
  const gists = response.json;
  if (Array.isArray(gists)) {
    for (const gist of gists) {
      if (gist.files && (gist.files[GIST_FILENAME] || ((_a = gist.description) == null ? void 0 : _a.toLowerCase().includes("exam app")))) {
        return gist.id;
      }
    }
  }
  return null;
}
async function createExamAppGist(token) {
  if (!token || !token.trim()) {
    throw new Error("Gist olu\u015Fturmak i\xE7in ge\xE7erli bir token gerekiyor.");
  }
  const initialPayload = {
    version: 2,
    sources: [],
    deletedSourceIds: [],
    stats: {},
    totalStats: {},
    recentTests: {},
    settings: {}
  };
  const reqParams = {
    url: `${GITHUB_API_BASE}/gists`,
    method: "POST",
    headers: {
      "Authorization": `Bearer ${token.trim()}`,
      "Accept": "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({
      description: "Exam App - User Study & Resource Data Sync (via Obsidian)",
      public: false,
      files: {
        [GIST_FILENAME]: {
          content: JSON.stringify(initialPayload, null, 2)
        }
      }
    })
  };
  const response = await (0, import_obsidian.requestUrl)(reqParams);
  if (response.status !== 201 && response.status !== 200) {
    throw new Error(`ExamApp Gist olu\u015Fturulamad\u0131 (HTTP ${response.status})`);
  }
  return response.json.id;
}

// src/fileScanner.ts
var import_obsidian2 = require("obsidian");

// src/schemaValidator.ts
var VALID_TYPES = /* @__PURE__ */ new Set(["single_choice", "multiple_choice", "true_false", "text_input", "text", "open_ended", "fill_in_the_blank", "flashcard"]);
function validateExamSchema(data) {
  var _a;
  if (!data || typeof data !== "object" || Array.isArray(data)) {
    return { valid: false, isExamAppSource: false };
  }
  if (!data.id || typeof data.id !== "string") {
    return { valid: false, isExamAppSource: false };
  }
  if (!Array.isArray(data.questions)) {
    return { valid: false, isExamAppSource: false };
  }
  for (let i = 0; i < data.questions.length; i++) {
    const q = data.questions[i];
    if (q.id === void 0 || q.id === null) {
      return { valid: false, isExamAppSource: true };
    }
    const text = ((_a = q.content) == null ? void 0 : _a.text) || q.text;
    if (!text || String(text).trim() === "") {
      return { valid: false, isExamAppSource: true };
    }
    if (!q.type || !VALID_TYPES.has(q.type)) {
      return { valid: false, isExamAppSource: true };
    }
    if (q.type !== "flashcard" && (!q.answer || typeof q.answer !== "object")) {
      return { valid: false, isExamAppSource: true };
    }
  }
  return { valid: true, isExamAppSource: true };
}

// src/fileScanner.ts
async function scanLocalSources(app, folderPath) {
  const targetFolder = app.vault.getAbstractFileByPath(folderPath);
  if (!targetFolder || !(targetFolder instanceof import_obsidian2.TFolder)) {
    console.warn(`[ExamApp Sync] Hedef klas\xF6r bulunamad\u0131: ${folderPath}`);
    return [];
  }
  const validSources = [];
  for (const child of targetFolder.children) {
    if (child instanceof import_obsidian2.TFile && child.extension === "json") {
      try {
        const content = await app.vault.read(child);
        const data = JSON.parse(content);
        const { valid, isExamAppSource } = validateExamSchema(data);
        if (isExamAppSource && valid) {
          validSources.push(data);
        } else if (isExamAppSource && !valid) {
          console.warn(`[ExamApp Sync] Dosya (${child.path}) ExamApp yap\u0131s\u0131na benziyor fakat \u015Fema hatas\u0131 i\xE7eriyor. Atlan\u0131yor.`);
        }
      } catch (err) {
        console.error(`[ExamApp Sync] JSON okuma hatas\u0131 (${child.path}):`, err);
      }
    }
  }
  return validSources;
}
async function writeLocalSources(app, folderPath, sources) {
  const targetFolder = app.vault.getAbstractFileByPath(folderPath);
  if (!targetFolder || !(targetFolder instanceof import_obsidian2.TFolder)) {
    try {
      await app.vault.createFolder(folderPath);
    } catch (e) {
      console.error(`[ExamApp Sync] Hedef klas\xF6r olu\u015Fturulamad\u0131: ${folderPath}`, e);
      return;
    }
  }
  for (const source of sources) {
    const safeName = (source.name || source.id || "Unknown_Source").replace(/[\\/:*?"<>|]/g, "_");
    const filePath = `${folderPath}/${safeName}_${source.id.substring(0, 8)}.json`;
    const content = JSON.stringify(source, null, 2);
    const existingFile = app.vault.getAbstractFileByPath(filePath);
    if (existingFile instanceof import_obsidian2.TFile) {
      await app.vault.modify(existingFile, content);
    } else {
      await app.vault.create(filePath, content);
    }
  }
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  githubToken: "",
  gistId: "",
  localFolderPath: "ExamApp Sync",
  githubUsername: "",
  autoSyncOnStartup: false,
  showNotifications: true
};
var GITHUB_SVG_ICON = `<svg height="16" width="16" viewBox="0 0 16 16" version="1.1" fill="currentColor" style="vertical-align: text-bottom; margin-right: 6px;"><path d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z"></path></svg>`;
var ExamAppGistSyncSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    var _a;
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ExamApp Gist Sync - Ayarlar" });
    containerEl.createEl("h3", { text: "\u{1F511} GitHub Oturum Y\xF6netimi" });
    if (this.plugin.settings.githubToken && this.plugin.settings.githubUsername) {
      const accountCard = containerEl.createDiv({ cls: "examapp-account-card" });
      accountCard.style.padding = "14px";
      accountCard.style.borderRadius = "8px";
      accountCard.style.backgroundColor = "var(--background-secondary)";
      accountCard.style.border = "1px solid var(--background-modifier-border)";
      accountCard.style.marginBottom = "18px";
      const statusEl = accountCard.createEl("div");
      statusEl.innerHTML = `${GITHUB_SVG_ICON}<strong>Ba\u011Fl\u0131 Hesap:</strong> @${this.plugin.settings.githubUsername} <span style="color: var(--text-success); font-weight: bold; margin-left: 8px;">\u25CF Aktif</span>`;
      statusEl.style.fontSize = "1.05em";
      statusEl.style.marginBottom = "12px";
      new import_obsidian3.Setting(accountCard).setName("Oturumu Kapat").setDesc("GitHub ba\u011Flant\u0131s\u0131n\u0131 ve kaydedilen Gist kimli\u011Fini kald\u0131r\u0131r.").addButton(
        (button) => button.setButtonText("Oturumu Kapat").setWarning().onClick(async () => {
          this.plugin.settings.githubToken = "";
          this.plugin.settings.githubUsername = "";
          this.plugin.settings.gistId = "";
          await this.plugin.saveSettings();
          new import_obsidian3.Notice("\u{1F512} GitHub oturumu kapat\u0131ld\u0131.");
          this.display();
        })
      );
    } else {
      let inputToken = "";
      let showInfo = false;
      const loginSetting = new import_obsidian3.Setting(containerEl);
      const nameEl = loginSetting.nameEl;
      nameEl.innerHTML = `GitHub Personal Access Token (PAT) <span class="examapp-info-icon" style="cursor: pointer; color: var(--text-muted); font-size: 0.9em; margin-left: 6px; padding: 2px 6px; border-radius: 50%; background: var(--background-modifier-border);" title="PAT Nedir ve Nas\u0131l Al\u0131n\u0131r?">\u2139\uFE0F</span>`;
      loginSetting.setDesc('GitHub hesab\u0131n\u0131zdan al\u0131nan ("gist" yetkisine sahip) token. Oturum a\xE7\u0131ld\u0131\u011F\u0131nda senkronizasyon otomatik ba\u015Flar.');
      loginSetting.addText(
        (text) => text.setPlaceholder("ghp_...").setValue(this.plugin.settings.githubToken).onChange((val) => {
          inputToken = val.trim();
        })
      );
      (_a = loginSetting.controlEl.querySelector("input")) == null ? void 0 : _a.setAttribute("type", "password");
      const infoBox = containerEl.createDiv({ cls: "examapp-pat-info-box" });
      infoBox.style.display = "none";
      infoBox.style.padding = "14px 16px";
      infoBox.style.borderRadius = "8px";
      infoBox.style.backgroundColor = "var(--background-secondary)";
      infoBox.style.borderLeft = "4px solid var(--interactive-accent)";
      infoBox.style.marginBottom = "16px";
      infoBox.style.fontSize = "0.92em";
      infoBox.style.lineHeight = "1.5";
      infoBox.innerHTML = `
				<div style="font-weight: bold; font-size: 1.05em; margin-bottom: 6px;">\u2139\uFE0F PAT (Personal Access Token) Nedir ve Nas\u0131l Al\u0131n\u0131r?</div>
				<p style="margin: 0 0 10px 0; color: var(--text-normal);">
					<strong>Nedir?</strong> GitHub, g\xFCvenlik gerek\xE7esiyle uygulamalar\u0131n kullan\u0131c\u0131 ad\u0131/\u015Fifre ile do\u011Frudan giri\u015F yapmas\u0131n\u0131 yasaklar. 
					PAT, ana \u015Fifrenizi vermeden sadece soru havuzlar\u0131n\u0131z\u0131 yedeklememiz i\xE7in verilen <strong>g\xFCvenli bir eri\u015Fim anahtar\u0131d\u0131r</strong>.
				</p>
				<div style="font-weight: bold; margin-bottom: 4px;">\u{1F680} 3 Ad\u0131mda Kolayca Al\u0131n:</div>
				<ol style="margin: 0 0 12px 18px; padding: 0;">
					<li style="margin-bottom: 4px;">
						<a href="https://github.com/settings/tokens/new?scopes=gist&description=Obsidian%20ExamApp%20Sync" target="_blank" style="color: var(--text-accent); font-weight: bold; text-decoration: underline;">
							\u{1F517} Buraya T\u0131klayarak GitHub Token Olu\u015Fturma Sayfas\u0131n\u0131 A\xE7\u0131n
						</a>
						<em>(Gereken "gist" yetkisi otomatik se\xE7ili gelecektir)</em>
					</li>
					<li style="margin-bottom: 4px;">Sayfan\u0131n en alt\u0131ndaki <strong>"Generate token"</strong> butonuna bas\u0131n.</li>
					<li>Ekranda \xE7\u0131kan <code>ghp_...</code> ile ba\u015Flayan kodu kopyalay\u0131p yukar\u0131daki alana yap\u0131\u015Ft\u0131r\u0131n.</li>
				</ol>
			`;
      const iconEl = nameEl.querySelector(".examapp-info-icon");
      if (iconEl) {
        iconEl.addEventListener("click", () => {
          showInfo = !showInfo;
          infoBox.style.display = showInfo ? "block" : "none";
        });
      }
      loginSetting.addButton((button) => {
        button.buttonEl.innerHTML = `${GITHUB_SVG_ICON} GitHub ile Oturum A\xE7`;
        button.buttonEl.style.backgroundColor = "#24292f";
        button.buttonEl.style.color = "#ffffff";
        button.buttonEl.style.fontWeight = "600";
        button.buttonEl.style.padding = "6px 14px";
        button.buttonEl.style.borderRadius = "6px";
        button.buttonEl.style.border = "none";
        button.buttonEl.style.cursor = "pointer";
        button.buttonEl.style.display = "inline-flex";
        button.buttonEl.style.alignItems = "center";
        button.buttonEl.style.transition = "background-color 0.2s ease";
        button.buttonEl.addEventListener("mouseenter", () => {
          button.buttonEl.style.backgroundColor = "#333942";
        });
        button.buttonEl.addEventListener("mouseleave", () => {
          button.buttonEl.style.backgroundColor = "#24292f";
        });
        button.onClick(async () => {
          const tokenToUse = inputToken || this.plugin.settings.githubToken;
          if (!tokenToUse) {
            new import_obsidian3.Notice("\u26A0\uFE0F L\xFCtfen bir GitHub PAT token girin.");
            return;
          }
          button.setDisabled(true);
          button.buttonEl.innerHTML = `${GITHUB_SVG_ICON} Oturum A\xE7\u0131l\u0131yor...`;
          try {
            const user = await fetchGitHubUser(tokenToUse);
            this.plugin.settings.githubToken = tokenToUse;
            this.plugin.settings.githubUsername = user.login;
            let detectedGistId = await findExamAppGist(tokenToUse);
            if (!detectedGistId) {
              detectedGistId = await createExamAppGist(tokenToUse);
            }
            this.plugin.settings.gistId = detectedGistId;
            await this.plugin.saveSettings();
            new import_obsidian3.Notice(`\u2705 Ho\u015F geldiniz @${user.login}! Oturum a\xE7\u0131ld\u0131. Senkronizasyon ba\u015Flat\u0131l\u0131yor...`);
            await this.plugin.syncWithGist();
            this.display();
          } catch (err) {
            console.error("[ExamApp Login Error]", err);
            new import_obsidian3.Notice(`\u274C Oturum A\xE7ma Ba\u015Far\u0131s\u0131z: ${err.message}`);
          } finally {
            button.setDisabled(false);
            button.buttonEl.innerHTML = `${GITHUB_SVG_ICON} GitHub ile Oturum A\xE7`;
          }
        });
      });
    }
    if (this.plugin.settings.githubToken) {
      containerEl.createEl("h3", { text: "\u2601\uFE0F Gist Durumu & Otomatik Tespit" });
      const gistCard = containerEl.createDiv();
      gistCard.style.padding = "12px";
      gistCard.style.borderRadius = "6px";
      gistCard.style.backgroundColor = "var(--background-secondary)";
      gistCard.style.marginBottom = "18px";
      if (this.plugin.settings.gistId) {
        const infoEl = gistCard.createEl("div");
        infoEl.innerHTML = `<strong>\u{1F7E2} Ba\u011Fl\u0131 Gist ID:</strong> <code>${this.plugin.settings.gistId}</code> <span style="color: var(--text-muted); font-size: 0.9em;">(Otomatik Ba\u011Fland\u0131)</span>`;
        infoEl.style.marginBottom = "10px";
      } else {
        const infoEl = gistCard.createEl("div");
        infoEl.innerHTML = `<strong>\u26A0\uFE0F Hen\xFCz bir ExamApp Gist ba\u011Fl\u0131 de\u011Fil.</strong>`;
        infoEl.style.color = "var(--text-accent)";
        infoEl.style.marginBottom = "10px";
      }
      new import_obsidian3.Setting(gistCard).setName("Gist Otomatik Yeniden Tara / Olu\u015Ftur").setDesc("Hesab\u0131n\u0131zdaki ExamApp Gist varl\u0131\u011F\u0131n\u0131 tarar veya yoksa otomatik olu\u015Fturur.").addButton(
        (btn) => btn.setButtonText("Yeniden Tara").onClick(async () => {
          try {
            const id = await findExamAppGist(this.plugin.settings.githubToken);
            if (id) {
              this.plugin.settings.gistId = id;
              await this.plugin.saveSettings();
              new import_obsidian3.Notice("\u2705 ExamApp Gist ba\u015Far\u0131yla tespit edildi!");
              this.display();
            } else {
              new import_obsidian3.Notice("\u26A0\uFE0F Hesab\u0131n\u0131zda hen\xFCz ExamApp Gist bulunamad\u0131.");
            }
          } catch (e) {
            new import_obsidian3.Notice(`\u274C Taramada hata: ${e.message}`);
          }
        })
      ).addButton(
        (btn) => btn.setButtonText("Yeni Gist Olu\u015Ftur").setCta().onClick(async () => {
          try {
            const newId = await createExamAppGist(this.plugin.settings.githubToken);
            this.plugin.settings.gistId = newId;
            await this.plugin.saveSettings();
            new import_obsidian3.Notice("\u{1F389} Yeni ExamApp Gist ba\u015Far\u0131yla olu\u015Fturuldu ve ba\u011Fland\u0131!");
            this.display();
          } catch (e) {
            new import_obsidian3.Notice(`\u274C Gist olu\u015Fturma hatas\u0131: ${e.message}`);
          }
        })
      );
      const detailsEl = containerEl.createEl("details");
      detailsEl.style.marginBottom = "18px";
      detailsEl.style.cursor = "pointer";
      const summaryEl = detailsEl.createEl("summary", { text: "\u2699\uFE0F Geli\u015Fmi\u015F: Manuel Gist ID D\xFCzenleme" });
      summaryEl.style.color = "var(--text-muted)";
      summaryEl.style.fontWeight = "bold";
      new import_obsidian3.Setting(detailsEl).setName("Manuel Gist ID (\xD6zel)").setDesc("Gist ID otomatik tespit edilir. Yaln\u0131zca \xF6zel bir Gist ID zorlamak istiyorsan\u0131z de\u011Fi\u015Ftirin.").addText(
        (text) => text.setPlaceholder("e.g. 1a2b3c4d5e6f7g8h9i0j").setValue(this.plugin.settings.gistId).onChange(async (val) => {
          this.plugin.settings.gistId = val.trim();
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h3", { text: "\u{1F4C2} Vault Senkronizasyon Klas\xF6r\xFC" });
    new import_obsidian3.Setting(containerEl).setName("Klas\xF6r Yolu").setDesc('Senkronize edilecek JSON dosyalar\u0131n\u0131n bulundu\u011Fu Vault i\xE7i klas\xF6r. (Varsay\u0131lan: "ExamApp Sync")').addText(
      (text) => text.setPlaceholder("ExamApp Sync").setValue(this.plugin.settings.localFolderPath).onChange(async (val) => {
        this.plugin.settings.localFolderPath = val.trim() || "ExamApp Sync";
        await this.plugin.saveSettings();
      })
    );
    const schemaInfoBox = containerEl.createDiv();
    schemaInfoBox.style.padding = "10px 14px";
    schemaInfoBox.style.borderRadius = "6px";
    schemaInfoBox.style.backgroundColor = "var(--background-secondary)";
    schemaInfoBox.style.borderLeft = "4px solid var(--interactive-accent)";
    schemaInfoBox.style.marginBottom = "12px";
    schemaInfoBox.innerHTML = `\u2139\uFE0F <strong>\u015Eema G\xFCvenlik Filtresi:</strong> Bu klas\xF6r i\xE7erisindeki dosyalar taran\u0131rken sadece ge\xE7erli ExamApp soru \u015Femas\u0131na (<code>{ id, questions: [...] }</code>) sahip <code>.json</code> dosyalar\u0131 i\u015Flenir. Di\u011Fer uyumsuz JSON veya not dosyalar\u0131 g\xFCvenle atlan\u0131r.`;
    new import_obsidian3.Setting(containerEl).setName("Klas\xF6r Taramas\u0131n\u0131 Test Et").setDesc("Belirtilen klas\xF6rdeki uyumlu ExamApp soru havuzlar\u0131n\u0131 canl\u0131 olarak tarar ve say\u0131s\u0131n\u0131 do\u011Frular.").addButton(
      (btn) => btn.setButtonText("\u015Eimdi Tara ve Do\u011Frula").onClick(async () => {
        const sources = await scanLocalSources(this.app, this.plugin.settings.localFolderPath);
        new import_obsidian3.Notice(`\u{1F50D} Tarama Tamamland\u0131: "${this.plugin.settings.localFolderPath}" klas\xF6r\xFCnde ${sources.length} adet ge\xE7erli ExamApp soru havuzu bulundu.`);
      })
    );
    containerEl.createEl("h3", { text: "\u2699\uFE0F Genel Otomasyon Ayarlar\u0131" });
    new import_obsidian3.Setting(containerEl).setName("Obsidian A\xE7\u0131l\u0131\u015F\u0131nda Otomatik Senkronize Et").setDesc("Obsidian ba\u015Flat\u0131ld\u0131\u011F\u0131nda Gist senkronizasyonunu arka planda otomatik olarak tetikler.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSyncOnStartup).onChange(async (val) => {
        this.plugin.settings.autoSyncOnStartup = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Senkronizasyon Bildirimlerini G\xF6ster").setDesc("Senkronizasyon ba\u015Flad\u0131\u011F\u0131nda ve tamamland\u0131\u011F\u0131nda ekranda bilgi bildirimleri (toast Notice) g\xF6sterir.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showNotifications).onChange(async (val) => {
        this.plugin.settings.showNotifications = val;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/gistSync.ts
var import_obsidian4 = require("obsidian");
var GIST_FILENAME2 = "exam_app_backup.json";
var GITHUB_API_BASE2 = "https://api.github.com";
async function ensureGistId(settings) {
  if (!settings.githubToken) {
    throw new Error("GitHub PAT token tan\u0131ml\u0131 de\u011Fil. L\xFCtfen eklenti ayarlar\u0131ndan oturum a\xE7\u0131n.");
  }
  if (settings.gistId) {
    return settings.gistId;
  }
  const detectedId = await findExamAppGist(settings.githubToken);
  if (detectedId) {
    settings.gistId = detectedId;
    return detectedId;
  }
  const createdId = await createExamAppGist(settings.githubToken);
  settings.gistId = createdId;
  return createdId;
}
async function fetchGistData(settings) {
  const gistId = await ensureGistId(settings);
  const reqParams = {
    url: `${GITHUB_API_BASE2}/gists/${gistId}`,
    method: "GET",
    headers: {
      "Authorization": `Bearer ${settings.githubToken.trim()}`,
      "Accept": "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28"
    }
  };
  const response = await (0, import_obsidian4.requestUrl)(reqParams);
  if (response.status !== 200) {
    throw new Error(`GitHub Gist okuma hatas\u0131: ${response.status}`);
  }
  const gist = response.json;
  const file = gist.files && gist.files[GIST_FILENAME2];
  if (file && file.content) {
    return JSON.parse(file.content);
  }
  return {
    version: 2,
    sources: [],
    deletedSourceIds: [],
    stats: {},
    totalStats: {},
    recentTests: {},
    settings: {}
  };
}
async function pushGistData(settings, payload) {
  const gistId = await ensureGistId(settings);
  const reqParams = {
    url: `${GITHUB_API_BASE2}/gists/${gistId}`,
    method: "PATCH",
    headers: {
      "Authorization": `Bearer ${settings.githubToken.trim()}`,
      "Accept": "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({
      description: "Exam App - User Study & Resource Data Sync (via Obsidian)",
      files: {
        [GIST_FILENAME2]: {
          content: JSON.stringify(payload, null, 2)
        }
      }
    })
  };
  const response = await (0, import_obsidian4.requestUrl)(reqParams);
  if (response.status !== 200) {
    throw new Error(`GitHub Gist yazma hatas\u0131: ${response.status}`);
  }
}

// src/dataMerger.ts
function mergeSyncData(localSources, remotePayload) {
  let hasLocalChanges = false;
  const mergedDeletedIds = Array.from(/* @__PURE__ */ new Set([
    ...remotePayload.deletedSourceIds || []
  ]));
  const sourcesMap = /* @__PURE__ */ new Map();
  (remotePayload.sources || []).forEach((s) => {
    if (s && s.id && !mergedDeletedIds.includes(s.id)) {
      sourcesMap.set(s.id, s);
    }
  });
  (localSources || []).forEach((s) => {
    if (!s || !s.id || mergedDeletedIds.includes(s.id)) return;
    if (!sourcesMap.has(s.id)) {
      sourcesMap.set(s.id, s);
      hasLocalChanges = true;
    } else {
      const existing = sourcesMap.get(s.id);
      const localHasQuestions = Array.isArray(s.questions) && s.questions.length > 0;
      const existingHasQuestions = Array.isArray(existing.questions) && existing.questions.length > 0;
      if (!existingHasQuestions && localHasQuestions) {
        sourcesMap.set(s.id, s);
        hasLocalChanges = true;
      } else if (existingHasQuestions && !localHasQuestions) {
      } else if ((s.lastUsed || 0) > (existing.lastUsed || 0)) {
        sourcesMap.set(s.id, s);
        hasLocalChanges = true;
      }
    }
  });
  const mergedSources = Array.from(sourcesMap.values());
  return {
    version: remotePayload.version || 2,
    lastUpdated: Date.now(),
    sources: mergedSources,
    deletedSourceIds: mergedDeletedIds,
    stats: remotePayload.stats || {},
    totalStats: remotePayload.totalStats || {},
    recentTests: remotePayload.recentTests || [],
    settings: remotePayload.settings || {},
    hasLocalChanges
  };
}

// src/main.ts
var ExamAppGistSyncPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ExamAppGistSyncSettingTab(this.app, this));
    const ribbonIconEl = this.addRibbonIcon("refresh-cw", "ExamApp Sync", async () => {
      await this.syncWithGist();
    });
    ribbonIconEl.addClass("examapp-sync-ribbon-class");
    this.addCommand({
      id: "sync-examapp-gist",
      name: "Sync with ExamApp Gist",
      callback: async () => {
        await this.syncWithGist();
      }
    });
    if (this.settings.autoSyncOnStartup && this.settings.githubToken) {
      this.app.workspace.onLayoutReady(async () => {
        await this.syncWithGist(true);
      });
    }
  }
  onunload() {
  }
  async syncWithGist(isAutoSync = false) {
    if (!this.settings.githubToken) {
      if (!isAutoSync && this.settings.showNotifications) {
        new import_obsidian5.Notice("\u274C ExamApp Sync: L\xFCtfen \xF6nce eklenti ayarlar\u0131ndan GitHub hesab\u0131n\u0131zla oturum a\xE7\u0131n.");
      }
      return;
    }
    if (this.settings.showNotifications) {
      new import_obsidian5.Notice("\u23F3 ExamApp: Senkronizasyon ba\u015Flat\u0131l\u0131yor...");
    }
    try {
      const remoteData = await fetchGistData(this.settings);
      await this.saveSettings();
      const localSources = await scanLocalSources(this.app, this.settings.localFolderPath);
      const mergedData = mergeSyncData(localSources, remoteData);
      await pushGistData(this.settings, mergedData);
      await writeLocalSources(this.app, this.settings.localFolderPath, mergedData.sources);
      if (this.settings.showNotifications) {
        new import_obsidian5.Notice(`\u2705 ExamApp: Senkronizasyon Ba\u015Far\u0131l\u0131! (${mergedData.sources.length} havuz senkronize edildi)`);
      }
    } catch (error) {
      console.error("[ExamApp Sync] Hata:", error);
      if (this.settings.showNotifications) {
        new import_obsidian5.Notice(`\u274C ExamApp: Senkronizasyon hatas\u0131! ${error.message}`);
      }
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
